spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
#  jackson:
#    default-property-inclusion: non_null  是null的字段不返回
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans=true:

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /Users/baidu/Desktop/wan/sell/logs/
server:
  servlet:
    context-path: /sell
  port: 8080
#  file: /Users/baidu/Desktop/wan/sell/logs/

wechat:
  mpAppId: wx33f8afccdd1a3a9b
  mpAppSecret: 6016b39b93b736a1aa5582fbcdbc4ae8
  mchId: 1404269502
  mchKey:
  keyPath: